### ISSUE TITLE
Long list items cause item label to be along on its line

### ISSUE THREAD

**Issue by akerbos** [grrinchas/aliquam#4]
Markdown renderers will routinely create code like this:

```html
<ul>
  <li>
    <p>First paragraph of a long item.</p>
    <p>Second paragraph of a long item.</p>
  </li>
  <li>
    <p>A lonely paragraph</p>
  </li>
</ul>
```

Which looks like this in aliquam:

![screenshot from 2016-11-08 22-21-09](https://cloud.githubusercontent.com/assets/1488534/20117630/bb6a761a-a601-11e6-8fea-195794c604f6.png)

Is that intentional?

**Comment by grrinchas** [comment]
Yes.  This is intentional. Paragraph tag is a block element so it starts at new line, also I added extra bottom margin to it. If you put it inside of  list item you will get rendering like that.

**Comment by akerbos** [comment]
Okay. Hacking it is!

FWIW, this does by no means happen with every theme. Just observe how Github deals with such items:
- A long item.
  
  With multiple paragraphs
- And a short one.

This is generally the layout I expect. Lists kind of lose their purpose if you have to scroll to find out if you're in an item or not; plus the end of the list is not clear without item indentation.
